# yamllint disable rule:line-length
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        files: ^.+\.py$

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.36.0
    hooks:
      - id: markdownlint

minimum_pre_commit_version: !!str 3.4
